### ISSUE TITLE
Docker image broken

### ISSUE THREAD

**Issue by AudriusButkevicius** [urm8/IsortConnect#8]
Looking at https://pypi.org/project/isortd/

I've started isortd via docker, but I am getting

```
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/opt/pypy/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/opt/pypy/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/opt/pypy/site-packages/isortd/main.py", line 84, in handle
    out = code(code=in_, config=cfg, file_path=Path(fp) if fp else None)
  File "/opt/pypy/site-packages/isort/api.py", line 82, in sort_code_string
    show_diff=show_diff,
  File "/opt/pypy/site-packages/isort/api.py", line 168, in sort_stream
    if not disregard_skip and file_path and config.is_skipped(file_path):
  File "/opt/pypy/site-packages/isort/settings.py", line 524, in is_skipped
    ["git", "-C", str(file_path.parent), "check-ignore", "--quiet", os_path]
  File "/opt/pypy/lib-python/3/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/pypy/lib-python/3/subprocess.py", line 815, in __init__
    restore_signals, start_new_session)
  File "/opt/pypy/lib-python/3/subprocess.py", line 1579, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git': 'git'
```

when saving files.

**Comment by AudriusButkevicius** [comment]
I just realised that isort is trying to check if the files should be ignored based on `skip_gitignore=true` and that clearly won't work inside of a container unless I mount the code somewhere.

Is there a way to for isort/isortd/isortconnect to ignore based on file patterns like black[d]?
